import asyncio
import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import httpx
import uvicorn

from app.core.config import settings
from app.routers import webhooks, chat
from app.services import embeddings
from app.services.vectordb import init_collection, get_client

import inngest.fast_api
from app.inngest.client import inngest_client
from app.inngest import indexing, auto_pr

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(webhooks.router, tags=["webhooks"])
app.include_router(chat.router, tags=["chat"])


def _normalize_service_status(ok: bool):
    return "operational" if ok else "offline"


async def _check_embedding_service():
    if not settings.google_api_key:
        return False, "Google API key missing"

    try:
        await asyncio.wait_for(embeddings.create_embedding("health-check"), timeout=8)
        return True, "Embedding API reachable"
    except Exception as e:
        return False, str(e)


def _check_workflow_orchestrator():
    try:
        mounted = any(
            getattr(route, "path", None) == "/api/inngest" for route in app.routes
        )
        if mounted:
            return True, "Inngest endpoint mounted"
        return False, "Inngest endpoint not mounted"
    except Exception as e:
        return False, str(e)


async def _check_billing_provider():
    key_id = os.getenv("RAZORPAY_KEY_ID")
    key_secret = os.getenv("RAZORPAY_KEY_SECRET")
    if not key_id or not key_secret:
        return False, "Razorpay credentials missing"

    try:
        auth = (key_id, key_secret)
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(
                "https://api.razorpay.com/v1/items?count=1",
                auth=auth,
            )

        if response.status_code < 400:
            return True, "Razorpay API reachable"

        return False, f"Razorpay API returned {response.status_code}"
    except Exception as e:
        return False, str(e)


def _build_status_feed(
    qdrant_ok: bool,
    qdrant_error: str | None,
    embedding_ok: bool,
    embedding_detail: str,
    workflow_ok: bool,
    workflow_detail: str,
    billing_ok: bool,
    billing_detail: str,
):
    google_configured = bool(settings.google_api_key)

    services = {
        "backend_api": {
            "status": "operational",
            "detail": "FastAPI is running",
        },
        "workflow_orchestrator": {
            "status": _normalize_service_status(workflow_ok),
            "detail": workflow_detail,
        },
        "code_chunker": {
            "status": "operational",
            "detail": "Chunker module is available",
        },
        "embedding_service": {
            "status": _normalize_service_status(embedding_ok),
            "detail": embedding_detail,
        },
        "vector_db": {
            "status": _normalize_service_status(qdrant_ok),
            "detail": "Qdrant reachable" if qdrant_ok else (qdrant_error or "Qdrant unavailable"),
        },
        "llm_provider": {
            "status": _normalize_service_status(google_configured),
            "detail": "Google API key configured" if google_configured else "Google API key missing",
        },
        "billing_provider": {
            "status": _normalize_service_status(billing_ok),
            "detail": billing_detail,
        },
        "status_feed": {
            "status": "operational",
            "detail": "Generated by backend /status-feed",
        },
    }

    has_offline = any(service["status"] == "offline" for service in services.values())
    overall_status = "degraded" if has_offline else "operational"

    return {
        "status": overall_status,
        "services": services,
    }

@app.on_event("startup")
async def startup():
    init_collection()


@app.get("/")
def root():
    return {"message": "BugHop backend"}


@app.get("/health")
async def health_check():
    from fastapi.responses import JSONResponse

    checks = {
        "server": "ok",
        "qdrant": "ok",
    }

    try:
        qdrant_client = get_client()
        qdrant_client.get_collections()
    except Exception as e:
        checks["qdrant"] = str(e)

    has_errors = checks["qdrant"] != "ok"

    if has_errors:
        return JSONResponse(
            status_code=500,
            content={"status": "unhealthy", "checks": checks}
        )

    return {"status": "healthy", "checks": checks}


@app.get("/status-feed")
async def status_feed():
    qdrant_ok = True
    qdrant_error = None

    try:
        qdrant_client = get_client()
        qdrant_client.get_collections()
    except Exception as e:
        qdrant_ok = False
        qdrant_error = str(e)

    embedding_ok, embedding_detail = await _check_embedding_service()
    workflow_ok, workflow_detail = _check_workflow_orchestrator()
    billing_ok, billing_detail = await _check_billing_provider()

    return _build_status_feed(
        qdrant_ok=qdrant_ok,
        qdrant_error=qdrant_error,
        embedding_ok=embedding_ok,
        embedding_detail=embedding_detail,
        workflow_ok=workflow_ok,
        workflow_detail=workflow_detail,
        billing_ok=billing_ok,
        billing_detail=billing_detail,
    )

inngest.fast_api.serve(app, inngest_client, [indexing.handle_installation, auto_pr.handle_auto_pr])

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
